# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RecoveryBuddy' do

pod 'Parse'
pod 'ParseUI'
pod 'MBCalendarKit', '~>3.0.4'
pod 'YLProgressBar', '~> 3.8.1'
pod 'Bond', '4.3.0'
pod 'MMDrawerController', '~> 0.5.7'
end

target 'RecoveryBuddyTests' do

end

